added endPoints to token logic
wizelineacademy/itesm-socioformador-ago-dec-2023-team-01 pull request #65
Opened 2023-11-10 17:16 UTC by pabloerhard

2023-11-10 17:48 UTC, NicoHwpo requested changes
cambiar todo los comentarios...
- logicas van en servicio
- en el repo literal solo va gets, updates y posts...
- en el servicio haces todo lo de añadir tokens, quitar tokens, etc... y en el repo solo mandas el nuevo objeto ya actualizaco para hacer el update

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/group/groupController.ts
> + * '/api/group/set-tokens-to-group/{id}/{amount}':
aqui debe ser .../group/{groupId}/set-tokens-to-group/{amount}

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/group/groupController.ts
> +groupRouter.patch('/set-tokens-to-group/:id/:amount', async (req, res) => {
aca tocaria cambiarlo a lo de arriba.../:groupId/set-tokens-to-group/:amount

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/group/groupRepository.ts
>          return token;
aca segun la logica que habiamos hablado ayer, no deberia ser find first... porque te va a traer el token mas recientemente creado... pero segun lo que hablamos ayer, el usuario va a poder tener muchos tokens activos... entonces hay que cambiarlo a token.findMany. y luego despues de obeter los tokens, ya verificas que cada uno este todavia valio con el expires at

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/group/groupRepository.ts
> +  async setTokensToUsersFromGroup(
esto deberia estar en el servicio... en el servicio haces el 
` users =
      await groupRepository.findUsersInGroupByIdOrName(groupIdOrName);`
  y cuadno ya tengas los usuarios, ahi ya llamas al `setTokensToUsersFromGroup`.
  yo se que se puede hacer todo de una en el repo... pero la gracia del servicio es que ahi hagas la logica de traerte los usuarios del grupo y luego ya mandes a llamar la otra funcion del repo... un metodo del repo no debe quedar pesada, no debe tener "logica" de traerse usuarios ahi dentro de ella...

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/token/tokenRepository.ts
> +  async decrementCurrentAmountToken(
aca lo mismo de lo de la logica...
separa el `const token = await prisma.token.findUnique({
      where: {
        id: Number(tokenId),
      },
    });`
    del metodo. 
    En el repo haz un `getTokenById()`
    y pues en el service vas a traerte el token primero, y luego haces esta logica: `const newAmount = Math.max(0, token.currentAmount - amount);`
y luego solo mandas a llamar a un update...

entonces recapitulando:
- crea un metodo de getTokenById
- crea un metodo de updateTokenById
- en el service del token crea:
        - metodo de decrementCurrentAmountToken y dentro de ese metodo haz:
                - llamada al repo con getTokenById
                - luego cuando ya tengas el token, haces la logica de `const newAmount = Math.max(0, token.currentAmount - amount);`
                - luego de esa logica, ya mandas a llamar al repo otra vez con el update con el token actualizado

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/token/tokenRepository.ts
> +  async addTokensToUser(
aca lo mismo de lo de decrement...
crea en el servicio el metodo de `addTokensToUser`
y dentroo de él llamas al getTokenById, luego le sumas el amount y luego mandas a llamar el updateToken

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/user/userController.ts
> + * '/api/users/substract-token/{userId}/{amount}':
aca lo mismo del group controller... siguiendo los formatos de apis REST, para ser mas entendible el enpoint, tienes que tener el 'dominio' luego el id, luego la accion y luego la cantidad
en este caso el dominio seria el user...
entonces el url queda .../users/{userId}/substract-token/{amount}

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/user/userController.ts
> +  '/substract-token/:userId/:amount',
aca habria que cambiar el url a lo de /:userId/substract-token/:amount

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/user/userController.ts
> + * '/api/users/add-to-token/{userId}/{amount}':
aca lo mismo de lo del substract... lo de cambiar el url

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/user/userController.ts
> +  '/add-to-token/:userId/:amount',
aca tambien habria que cambiar el url

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/user/userRepository.ts
> +  async substractFromUserToken(
nooooo. 
Aca el mismo comentario de lo del servicio del token... toda la logica debe ser en el service.
el repo debe quedar lo mas simple posible... puros gets, posts y updates...
en el userService crea el metodo de `substractFromUserToken` y ahi adentro te traes el token del usuario `getUserCurrentToken`... y luego de traertelo mandas a llamar al `tokenService.decrementCurrentAmountToken` (este metodo es el nuevo del comentario pasado sobre el token service)

2023-11-10 17:48 UTC, NicoHwpo commented on backend/src/modules/user/userRepository.ts
> +  async addToUserToken(
aca lo mismo del substract... hacerlo en el servicio... no en el repo

2023-11-10 17:49 UTC, pabloerhard commented on backend/src/modules/group/groupRepository.ts
>          return token;
Lo cambiamos

2023-11-11 22:59 UTC, NicoHwpo approved these changes
Nice. looks functional.

2023-11-11 23:09 UTC, merged